---
directories:
- directory: "/home/johdin/tmp/backuplab/"
  retention-policy: clear-local
  rules:
  - rule: exclude-directory
    directory: "/home/johdin/tmp/backuplab/exclude/"
global-rules:
- rule: exclude-symlinks
- rule: exclude-hidden-files
